#ifndef WORD_SEARCH_DATASET_H
#define WORD_SEARCH_DATASET_H

#include <Arduino.h>
#include "WordSearchGen.h"

struct ThemeDef {
    const char* name;
    const char* words[12];
};

static const size_t NUM_WS_THEMES_PER_DIFF = 50;

static const ThemeDef EASY_THEMES[NUM_WS_THEMES_PER_DIFF] PROGMEM = {
    {
        "Farm Animals",
        {"HORSE", "SHEEP", "CHICK", "DUCKS", "GOATS", "CALVES", "PONY", "MULES", "LLAMA", "BUNNY", "TURKEY", "PIGLET"}
    },
    {
        "Breakfast",
        {"TOAST", "BACON", "BAGEL", "JUICE", "MILKS", "CREPE", "WAFFLE", "FRUIT", "JELLY", "BUTTER", "CEREAL", "MUFFIN"}
    },
    {
        "Colors",
        {"BLACK", "WHITE", "GREEN", "AMBER", "BROWN", "PURPLE", "SILVER", "YELLOW", "ORANGE", "VIOLET", "BRONZE", "GOLDEN"}
    },
    {
        "Sweet Treats",
        {"CANDY", "DONUT", "FUDGE", "JELLY", "MINTS", "PASTRY", "COOKIE", "TAFFY", "SUNDAE", "SUGAR", "SWEETS", "WAFER"}
    },
    {
        "Weather",
        {"CLOUDS", "FROST", "STORMS", "SUNNY", "RAINS", "SNOWY", "WINDS", "SLEET", "BREEZE", "CHILLY", "SHOWER", "WARMTH"}
    },
    {
        "Playground",
        {"SWINGS", "SLIDES", "SEESAW", "CLIMB", "HOOPS", "BALLS", "BENCH", "GAMES", "CHASE", "TUNNEL", "RINGS", "VAULT"}
    },
    {
        "Pets at Home",
        {"PUPPY", "KITTEN", "PARROT", "FERRET", "LIZARD", "CANARY", "TURTLE", "POODLE", "RABBIT", "BEAGLE", "GECKO", "FELINE"}
    },
    {
        "Garden Blooms",
        {"TULIPS", "DAISY", "ROSES", "ORCHID", "PANSY", "LILIES", "LOTUS", "CLOVER", "VIOLET", "POPPY", "PEONY", "BLOOM"}
    },
    {
        "Shapes & Math",
        {"SQUARE", "CIRCLE", "VERTEX", "SPHERE", "PRISM", "ANGLES", "POINTS", "SHAPES", "CURVES", "SECTOR", "CUBES", "CONES"}
    },
    {
        "Clothing",
        {"SHIRTS", "PANTS", "JACKET", "SOCKS", "SCARF", "GLOVES", "BOOTS", "SHOES", "DRESS", "BELTS", "VESTS", "HOODIE"}
    },
    {
        "Ocean Creatures",
        {"SHARKS", "WHALES", "SEALS", "URCHIN", "CRABS", "SQUIDS", "OTTERS", "CLAMS", "CORALS", "SHRIMP", "WALRUS", "SALMON"}
    },
    {
        "Camping Trip",
        {"TENTS", "CABIN", "TRAILS", "WOODS", "FLASKS", "BOOTS", "FLAME", "HIKING", "ROPES", "FLARES", "FOREST", "PACKS"}
    },
    {
        "Forest Trees",
        {"CEDARS", "BIRCH", "MAPLES", "WILLOW", "PINES", "SPRUCE", "WALNUT", "POPLAR", "TIMBER", "GROVE", "BRANCH", "LEAVES"}
    },
    {
        "Friendly Bugs",
        {"BEETLE", "CICADA", "WEEVIL", "SPIDER", "MOTHS", "HORNET", "MANTIS", "WASPS", "APHID", "DRAGON", "LOCUST", "FLEAS"}
    },
    {
        "Flying Birds",
        {"EAGLES", "ROBINS", "FALCON", "HAWKS", "DOVES", "RAVENS", "PARROT", "HERONS", "FINCH", "CANARY", "OSPREY", "PIGEON"}
    },
    {
        "In the Kitchen",
        {"SPOONS", "FORKS", "KNIVES", "PLATES", "BOWLS", "GLASS", "APRONS", "POTS", "MIXERS", "KETTLE", "DISHES", "LADLE"}
    },
    {
        "Sports & Play",
        {"SOCCER", "TENNIS", "HOCKEY", "RUGBY", "SKATER", "SWIMS", "SURFER", "TRACKS", "BOXING", "SKIING", "ROWING", "GOLFER"}
    },
    {
        "Beach Day",
        {"SANDS", "WAVES", "TIDES", "SHELLS", "TOWELS", "SHORES", "COASTS", "DUNES", "DRIFTS", "WATERS", "SURFS", "SPLASH"}
    },
    {
        "Circus Fun",
        {"CLOWNS", "TIGERS", "RINGS", "MAGICS", "HOOPS", "STILTS", "TRICKS", "PARADE", "CHEERS", "SHOWS", "LIGHTS", "JUGGLE"}
    },
    {
        "Fruit Basket",
        {"APPLES", "BANANA", "ORANGE", "CHERRY", "GRAPES", "MANGOS", "LEMONS", "PEACHY", "MELONS", "BERRY", "PAPAYA", "GUAVA"}
    },
    {
        "Vegetable Patch",
        {"CARROT", "RADISH", "TOMATO", "POTATO", "ONIONS", "PEPPER", "CELERY", "GARLIC", "BEANS", "TURNIP", "SQUASH", "GREENS"}
    },
    {
        "School Days",
        {"PENCIL", "ERASER", "RULERS", "DESKS", "BOOKS", "CHALKS", "RECESS", "LUNCH", "PAPERS", "PAINTS", "STUDY", "LESSON"}
    },
    {
        "Cozy Bedroom",
        {"PILLOW", "SHEETS", "CLOSET", "LAMPS", "ALARMS", "MIRROR", "QUILTS", "DUVET", "DRAPES", "CARPET", "STAND", "CHEST"}
    },
    {
        "Clean Bathroom",
        {"TOWELS", "SOAPS", "BRUSH", "SINKS", "FAUCET", "DRAINS", "SPONGE", "LOTION", "MIRROR", "BUBBLE", "SHOWER", "RINSE"}
    },
    {
        "Family Members",
        {"MOTHER", "FATHER", "SISTER", "COUSIN", "UNCLES", "NIECES", "NEPHEW", "FAMILY", "PARENT", "INFANT", "BABIES", "ELDER"}
    },
    {
        "Community Helpers",
        {"DOCTOR", "NURSES", "POLICE", "BAKERS", "PILOTS", "FARMER", "CHEFS", "JUDGES", "ARTIST", "DRIVER", "CLERKS", "GUARDS"}
    },
    {
        "Vehicles & Rides",
        {"TRUCKS", "TRAINS", "PLANES", "BOATS", "CANOES", "SUBWAY", "WAGONS", "FERRY", "CARTS", "GLIDER", "MOTOR", "YACHT"}
    },
    {
        "Picnic Outdoors",
        {"BASKET", "NAPKIN", "CHEESE", "BREADS", "DRINKS", "CRISPS", "SALADS", "COOLER", "SNACKS", "PLATES", "FRUITS", "SWEETS"}
    },
    {
        "Toolbox",
        {"HAMMER", "SCREWS", "NAILS", "DRILLS", "PLIERS", "WRENCH", "LEVELS", "CHISEL", "RULERS", "VISES", "MALLET", "BLADES"}
    },
    {
        "Castle Realm",
        {"KINGS", "QUEENS", "KNIGHT", "PRINCE", "CASTLE", "SHIELD", "SWORDS", "CROWNS", "TOWERS", "GUARDS", "THRONE", "PALACE"}
    },
    {
        "Birthday Bash",
        {"CANDLE", "RIBBON", "GAMES", "MUSICS", "DANCES", "CARDS", "CROWDS", "SMILES", "TREATS", "GIFTS", "PARTY", "FAVORS"}
    },
    {
        "Space Voyage",
        {"MOONS", "STARS", "PLANET", "COMETS", "ROCKET", "ORBITS", "METEOR", "CRATER", "COSMOS", "LUNAR", "SOLAR", "PROBES"}
    },
    {
        "Happy Feelings",
        {"JOYFUL", "CALMLY", "BRAVE", "SILLY", "PROUD", "CHEERY", "SMILES", "KINDLY", "SWEET", "MERRY", "GENTLE", "LAUGHS"}
    },
    {
        "Airport Travel",
        {"TICKET", "PILOTS", "PLANES", "RUNWAY", "TRAVEL", "GATES", "FLIGHT", "RADARS", "ENGINE", "CABINS", "WINGS", "CARGO"}
    },
    {
        "Jungle Trek",
        {"MONKEY", "TIGERS", "PARROT", "TOUCAN", "SNAKES", "JAGUAR", "LIANAS", "JUNGLE", "RIVERS", "BAMBOO", "CANOPY", "OCELOT"}
    },
    {
        "Treehouse",
        {"LADDER", "ROPES", "PLANKS", "SECRET", "SHACKS", "BRANCH", "SHADOW", "CLIMBS", "PERCH", "NESTLE", "POSTS", "WOODEN"}
    },
    {
        "Ice Cream Parlor",
        {"SCOOPS", "WAFFLE", "CONES", "CHERRY", "SYRUPS", "SUNDAE", "FLOATS", "SHAKES", "GELATO", "BOWLS", "FLAVOR", "CREAMY"}
    },
    {
        "Musical Sounds",
        {"GUITAR", "VIOLIN", "DRUMS", "PIANOS", "FLUTES", "HARPS", "BANJOS", "CELLOS", "ORGANS", "BUGLES", "HORNS", "CHORDS"}
    },
    {
        "Winter Cold",
        {"SLEDS", "MITTEN", "SCARFS", "ICICLE", "SKATES", "IGLOOS", "FROSTY", "POLARS", "DRIFTS", "BOOTS", "COATS", "TUNDRA"}
    },
    {
        "Spring Awakening",
        {"PUDDLE", "SPROUT", "SEEDS", "BREEZE", "ROBINS", "BLOOMS", "MEADOW", "GROWTH", "GREENS", "NESTS", "FLOWER", "SUNNY"}
    },
    {
        "Autumn Harvest",
        {"ACORNS", "LEAVES", "SQUASH", "CIDERS", "BARNS", "RAKES", "BALES", "CRISPY", "AMBERS", "CROPS", "FIELDS", "BASKET"}
    },
    {
        "Summer Sunshine",
        {"POOLS", "TOWELS", "SUNNY", "CRABS", "FLOATS", "DIVING", "SURFS", "PICNIC", "SHADES", "COOLER", "SPLASH", "BEACH"}
    },
    {
        "Desert Sands",
        {"CAMELS", "CACTUS", "DUNES", "OASIS", "PALMS", "GECKOS", "VIPERS", "SANDS", "COBRAS", "MIRAGE", "CANYON", "LIZARD"}
    },
    {
        "River Rapids",
        {"CANOES", "PADDLE", "RAPIDS", "RIVERS", "STREAM", "TROUTS", "OTTERS", "SHORES", "DRIFTS", "ROCKYS", "WATERS", "KAYAKS"}
    },
    {
        "Sci-Fi World",
        {"FLYING", "SAUCER", "ALIENS", "CRATER", "LASERS", "ROBOTS", "RADARS", "PROBES", "CLOAKS", "GALAXY", "CYBORG", "WARPS"}
    },
    {
        "Cozy Cabin",
        {"TEAPOT", "QUILTS", "CHAIRS", "PORCH", "HEARTH", "CANDLE", "PANTRY", "KETTLE", "NOOKS", "TIMBER", "LOGS", "STOVE"}
    },
    {
        "Super Heroes",
        {"FLIGHT", "SPEEDY", "SHIELD", "LASERS", "POWERS", "FORCES", "HEROES", "CLOAKS", "ENERGY", "VISION", "BLASTS", "CAPES"}
    },
    {
        "City Streets",
        {"STREET", "BRIDGE", "TOWERS", "PARKS", "STATUE", "SQUARE", "CORNER", "ALLEYS", "PLAZAS", "CLOCKS", "AVENUE", "MARKET"}
    },
    {
        "Wizards & Magic",
        {"WANDS", "POTION", "CLOAKS", "CHARMS", "SPELLS", "SCROLL", "WIZARD", "BROOMS", "SPARKS", "MYSTIC", "CASTS", "CURSE"}
    },
    {
        "Backyard Garden",
        {"LAWNS", "HOSES", "MOWERS", "FENCES", "PATIOS", "BENCH", "GRILLS", "TREES", "GRASSY", "WEEDS", "SHADES", "GARDEN"}
    },
};

static const ThemeDef MEDIUM_THEMES[NUM_WS_THEMES_PER_DIFF] PROGMEM = {
    {
        "Coffee Culture",
        {"ESPRESSO", "BARISTA", "ROASTED", "CARAMEL", "BREWING", "AROMATIC", "STEEPED", "POUROVER", "DRIPPER", "FROTHING", "BEANS", "GRINDER"}
    },
    {
        "Solar System",
        {"PLANETS", "JUPITER", "MERCURY", "NEPTUNE", "METEORS", "GALAXIES", "ASTEROID", "ORBITAL", "CRATERS", "ECLIPSE", "STELLAR", "VENUS"}
    },
    {
        "National Parks",
        {"CANYONS", "GEYSERS", "VALLEYS", "REDWOOD", "GLACIERS", "BOULDERS", "SUMMITS", "TRAILS", "FORESTS", "MEADOWS", "WILDFIRE", "TERRAIN"}
    },
    {
        "Detective Mystery",
        {"SLEUTHS", "CIPHERS", "SUSPECT", "ALIBIS", "SHADOWS", "MYSTERY", "PUZZLES", "EVIDENCE", "WITNESS", "INSPECT", "SECRETS", "CLUES"}
    },
    {
        "Baking Kitchen",
        {"DOUGH", "PRETZEL", "CINNAMON", "VANILLA", "NUTMEGS", "FLOURS", "BATTERS", "PASTRIES", "BRIOCHE", "ROLLING", "YEASTS", "CRUSTS"}
    },
    {
        "Marine Biology",
        {"DOLPHINS", "OCTOPUS", "JELLIES", "ANEMONE", "SEASTAR", "LOBSTER", "MOLLUSK", "MANATEE", "PLANKTON", "SEAHORSE", "WHALES", "TURTLE"}
    },
    {
        "Classical Music",
        {"SYMPHONY", "CONCERTO", "SONATAS", "MAESTRO", "QUARTET", "OVERTURE", "CADENZA", "HARMONY", "MELODIC", "VIOLINS", "PIANIST", "TEMPOS"}
    },
    {
        "Woodworking",
        {"HARDWOOD", "CHISELS", "JOINERY", "SHAPERS", "SAWHORSE", "TIMBERS", "DOWELING", "PLANING", "VARNISH", "SHAVING", "ROUTERS", "GROOVE"}
    },
    {
        "Board Games",
        {"PLAYCARD", "CHECKERS", "DOMINOES", "STRATEGY", "SPINNERS", "ROLLING", "SHUFFLE", "COUNTERS", "PAWNS", "TACTICS", "PLAYERS", "TILES"}
    },
    {
        "Architecture",
        {"COLUMNS", "FACADES", "ARCHWAY", "CAPITALS", "ROTUNDA", "BALCONY", "DOMICAL", "PILLARS", "CORRIDOR", "VAULTED", "PEDIMENT", "PARAPET"}
    },
    {
        "Road Trip",
        {"HIGHWAYS", "MOTORWAY", "ROADSIDE", "LUGGAGE", "JOURNEYS", "COMPASS", "TOURIST", "MILEAGE", "CRUISING", "SCENERY", "RESTSTOP", "CARAVAN"}
    },
    {
        "Photography",
        {"APERTURE", "SHUTTERS", "EXPOSURE", "FOCUSING", "PORTRAIT", "DARKROOM", "CONTRAST", "LIGHTING", "TRIPODS", "LENSES", "SNAPSHOT", "FRAMING"}
    },
    {
        "Botany & Flora",
        {"BLOSSOMS", "FOLIAGE", "SEEDLING", "NUTRIENT", "STAMENS", "PETIOLE", "CALYXES", "CONIFERS", "ROOTLETS", "BRANCHES", "SAPLINGS", "HARDSTEM"}
    },
    {
        "Desert Life",
        {"MEERKAT", "SCORPION", "SAGUARO", "COYOTES", "ROADRUNN", "ARIDITY", "HABOOB", "OASISES", "CANYONS", "BADLANDS", "MINERALS", "REPTILES"}
    },
    {
        "Rainforest",
        {"CANOPIES", "TROPICS", "JAGUARS", "TREEFROG", "HUMIDITY", "MONSOONS", "CREEPERS", "PARROTS", "TOUCANS", "FORESTS", "ORCHIDS", "HABITAT"}
    },
    {
        "Winter Sports",
        {"LUGEWAY", "BIATHLON", "CURLING", "BOBSLEDS", "SLALOM", "SKELETON", "SKATING", "CROSSING", "GLIDING", "DOWNHILL", "SKIERS", "BLIZZARD"}
    },
    {
        "Aviation",
        {"AIRPLANE", "AVIATOR", "ALTITUDE", "AVIONICS", "AIRSPEED", "TERMINAL", "AILERONS", "FUSELAGE", "COCKPITS", "FLIGHTS", "LANDINGS", "RUNWAYS"}
    },
    {
        "Mountain Peaks",
        {"RIDGES", "ALPINIST", "SUMMITED", "CREVASSE", "GLACIERS", "SNOWPACK", "MORAINES", "CLIFFS", "ALTITUDE", "CLIMBERS", "ASCENTS", "PLATEAU"}
    },
    {
        "Cinema & Film",
        {"DIRECTOR", "PRODUCER", "PREMIERE", "SCENARIO", "FEATURE", "ACTRESS", "COSTUMES", "LIGHTING", "SHOWTIME", "THEATERS", "CINEMAS", "STUDIOS"}
    },
    {
        "Medieval Lore",
        {"FORTRESS", "BALLISTA", "CATAPULT", "CROSSBOW", "PORTCULL", "BASTIONS", "CRUSADER", "CHIVALRY", "ARMORED", "SHIELDS", "LANCES", "HERALDRY"}
    },
    {
        "Gemstones",
        {"DIAMONDS", "SAPPHIRE", "EMERALDS", "AMETHYST", "QUARTZES", "PERIDOTS", "PERIDOT", "GARNETS", "TOPAZES", "LAPISLAZ", "CRYSTALS", "MINERALS"}
    },
    {
        "Ocean Voyage",
        {"CLIPPER", "SCHOONER", "MARINERS", "NAVIGATE", "COMPASS", "NAUTICAL", "HARBORS", "HORIZONS", "SEAFARER", "VOYAGING", "HEADLAND", "CAPTAIN"}
    },
    {
        "Bakery Treats",
        {"CRUFFIN", "BAGUETTE", "ECLAIRS", "MACARON", "TURNOVER", "SCONES", "MUFFINS", "CUPCAKES", "TARTLETS", "DANISHES", "STRUDEL", "MACAROON"}
    },
    {
        "Urban Transit",
        {"METROBUS", "COMMUTER", "TRANSFER", "STATIONS", "TROLLEYS", "SUBWAYS", "RAILCARS", "PLATFORM", "PASSENG", "EXPRESS", "CROSSING", "TERMINUS"}
    },
    {
        "Craft Brewing",
        {"FERMENT", "BREWERY", "ALEHOUSE", "MALTINGS", "BARRELS", "FLAVORS", "HOPSACK", "CASKING", "BEVERAGE", "DRAFTING", "PILSNER", "STOUTS"}
    },
    {
        "Tropical Isle",
        {"CORALINE", "LAGOONS", "ATOLLS", "COCONUTS", "HAMMOCKS", "BREEZES", "TROPICAL", "ISLANDS", "SEASHORE", "SUNSHINE", "PALMTREE", "PARADISE"}
    },
    {
        "Archaeology",
        {"ARTIFACT", "RELICS", "EXCAVATE", "TRENCHES", "MONUMENT", "PYRAMIDS", "ANCIENTS", "DIGSITES", "POTTERY", "INSCRIPT", "PHARAOH", "FOSSILS"}
    },
    {
        "Science Lab",
        {"REAGENTS", "BEAKERS", "TESTTUBE", "PIPETTES", "COMPOUND", "MOLECULE", "ELEMENTS", "REACTION", "CRYSTAL", "FORMULAS", "SPECIMEN", "SOLVENTS"}
    },
    {
        "Vintage Cars",
        {"ROADSTER", "CARBURET", "COUPELET", "SEDANET", "CHASSIS", "EXHAUSTS", "IGNITION", "RADIATOR", "GEARBOX", "CLUTCHES", "VINTAGE", "HORSEPOW"}
    },
    {
        "World Rivers",
        {"AMAZON", "COLORADO", "DANUBIAN", "RHINEWAY", "YANGTZE", "MEKONG", "GANGES", "VOLGARI", "ESTUARY", "DELTAIC", "RIVERBED", "TRIBUTAR"}
    },
    {
        "Mythology",
        {"CENTAURS", "MINOTAUR", "CERBERUS", "PEGASUS", "CYCLOPES", "OLYMPUS", "GORGONS", "VALKYRIE", "NEPTUNE", "PANTHEON", "TITANIC", "LEGENDS"}
    },
    {
        "Fitness & Gym",
        {"BARBELLS", "DUMBBELL", "WORKOUTS", "AEROBICS", "CALISTH", "STRENGTH", "CARDIO", "STRETCH", "KETTLEB", "TRAINING", "STAMINA", "FITNESS"}
    },
    {
        "Library Room",
        {"ARCHIVES", "CATALOGS", "ALCOVES", "EDITIONS", "VOLUMES", "CHAPTERS", "READING", "LENDING", "JOURNALS", "RESERVES", "BINDINGS", "BOOKCASE"}
    },
    {
        "Wildlife Park",
        {"ANTELOPE", "BUFFALO", "CHEETAHS", "ELEPHANT", "FLAMINGO", "GORILLAS", "HYENAS", "IMPALAS", "LEOPARDS", "MEERKATS", "OSTRICH", "ZEBRAS"}
    },
    {
        "Symphony Hall",
        {"WOODWIND", "TROMBONE", "BASSOONS", "TYMPANI", "DYNAMICS", "VIBRATO", "ALLEGRO", "ORCHESTR", "MAESTROS", "ENSEMBLE", "CONCERT", "OVERTURE"}
    },
    {
        "Tea Ceremony",
        {"INFUSER", "EARLGREY", "OOLONG", "DARJEEL", "JASMINE", "TEACUPS", "INFUSION", "HERBALS", "STEEPING", "MATCHA", "TEALEAF", "BREWING"}
    },
    {
        "Winter Cabin",
        {"FIREWOOD", "SNOWSHOE", "CHIMNEYS", "KINDLING", "THERMAL", "FLANNEL", "FROSTBIT", "BLANKETS", "HEATING", "CABINLIF", "SNOWFALL", "WINTERS"}
    },
    {
        "Rugged Coast",
        {"CLIFFTOP", "HEADLAND", "TIDEPOOL", "BARRIER", "SEAGULLS", "SEASTACK", "MARINAS", "SURFING", "COASTAL", "BREAKWAT", "SEASHORE", "CURRENT"}
    },
    {
        "Culinary Arts",
        {"SAUTEING", "POACHING", "BRAISING", "SIMMERED", "SEASONED", "JULIENNE", "ROASTING", "GARNISH", "MARINADE", "DEGLAZE", "REDUCING", "CULINARY"}
    },
    {
        "Volcanoes",
        {"MAGMATIC", "CALDERAS", "ERUPTION", "VOLCANIC", "OBSIDIAN", "PUMICE", "FUMAROLE", "CINDERS", "TEPHRAS", "BASALTIC", "CRATERS", "LAVABEDS"}
    },
    {
        "Clean Energy",
        {"SUNLIGHT", "TURBINES", "WINDMILL", "BIOFUELS", "HYDROPOW", "STORAGE", "INVERTER", "BIOPOWER", "GEOTHERM", "CURRENT", "ELECTRIC", "ECOLOGY"}
    },
    {
        "Rivers & Lakes",
        {"CATARACT", "OXBOWS", "STREAM", "HEADWAT", "TRIBUTAR", "ESTUARIN", "CHANNELS", "FRESHWAT", "LAKESIDE", "CURRENT", "STREAM", "MEANDERS"}
    },
    {
        "Forest Ecology",
        {"MUSHROOM", "NITROGEN", "MYCELIUM", "SAPROPHY", "CANOPIES", "WOODLAND", "HABITATS", "SEEDPOD", "NUTRIENT", "DETRITUS", "HABITAT", "WILDLIFE"}
    },
    {
        "Horology",
        {"PENDULUM", "CHRONOM", "ESCAPEM", "WATCHES", "CHIMING", "BALANCE", "QUARTZ", "SUNDIALS", "SUNCLOCK", "WATCHMA", "SPRING", "TICKING"}
    },
    {
        "Printing Press",
        {"TYPESET", "LETTERPR", "WOODCUTS", "PRINTING", "INKSTONE", "BOOKWORK", "ENGRAVE", "LITHOGR", "COLOPHON", "FOLIOS", "PAPERS", "IMPRINT"}
    },
    {
        "Castles & Moats",
        {"KEEPERS", "DRAWBRID", "BARBICAN", "RAMPARTS", "BATTLEM", "DUNGEONS", "TURRETS", "CITADEL", "MOATINGS", "WALLINGS", "TOWERS", "BASTION"}
    },
    {
        "Space Science",
        {"UNIVERSE", "NEBULAS", "TELESCOP", "SPECTRA", "REDSHIFT", "RADIANCE", "BIGBANG", "QUANTUM", "DARKMATT", "ORBITER", "PAYLOAD", "ASTRONOM"}
    },
    {
        "Farmstead",
        {"TRACTORS", "SILOING", "HARVESTS", "PASTURES", "HAYLOFTS", "GRANARY", "CORNROW", "ORCHARDS", "BARNYARD", "PLOWING", "BARNYARD", "WHEATEN"}
    },
    {
        "Carnival Midway",
        {"CAROUSEL", "FERRISWH", "ROLLER", "POPCORN", "SIDESHOW", "FUNHOUSE", "PRIZEWIN", "ARCADE", "MIDWAYS", "TICKETS", "SHOWMAN", "ACROBATS"}
    },
    {
        "Cellular Biology",
        {"BACTERIA", "PATHOGEN", "ORGANISM", "ANTIBODY", "IMMUNITY", "VACCINES", "CELLULAR", "GENETICS", "CULTURE", "MEMBRANE", "ENZYMES", "PROTEIN"}
    },
};

static const ThemeDef HARD_THEMES[NUM_WS_THEMES_PER_DIFF] PROGMEM = {
    {
        "Paleontology",
        {"FOSSILIZED", "TRICERATOP", "CARNIVORES", "EXCAVATION", "SEDIMENTARY", "SKELETONS", "PREHISTORIC", "AMMONITES", "PTEROSAURS", "JURASSIC", "HERBIVORES", "PALEONTOL"}
    },
    {
        "Renaissance Art",
        {"MASTERPIECE", "PERSPECTIVE", "SCULPTURES", "APPRENTICE", "PORTRAITURE", "WORKSHOPS", "FLORENTINE", "RENAISSANCE", "CHIAROSCUR", "FRESCOES", "NATURALISM", "ICONOGRAPHY"}
    },
    {
        "Oceanography",
        {"HYDROTHERM", "BATHYSCAPHE", "ECOSYSTEMS", "SUBMERSIBLE", "CONTINENTAL", "NAVIGATION", "ABYSSALZONE", "BENTHICZONE", "THERMOCLINE", "CRUSTACEAN", "OCEANOGRAP", "PELAGICZONE"}
    },
    {
        "Astrophysics",
        {"EXOPLANETS", "CONSTELLAT", "GRAVITATION", "OBSERVATORY", "SUPERNOVA", "RADIATION", "LIGHTYEARS", "CELESTIAL", "MAGNETOSPHE", "INTERSTELL", "ASTROPHYSIC", "BLACKHOLES"}
    },
    {
        "Atmospheric Science",
        {"STRATOSPHER", "TROPOSPHERE", "PRECIPITAT", "BAROMETERS", "ANEMOMETERS", "CONDENSAT", "TURBULENCE", "METEOROLOGY", "HUMIDITIES", "CYCLONICAL", "ATMOSPHERIC", "MESOSPHERE"}
    },
    {
        "Cryptography",
        {"ENCRYPTION", "DECRYPTION", "ALGORITHMS", "CIPHERTEXT", "ASYMMETRIC", "SIGNATURES", "PRIVATEKEY", "BLOCKCHAIN", "CRYPTOGRAPH", "HASHVALUES", "PERMUTATION", "CIPHERSUITE"}
    },
    {
        "Ancient Civilizations",
        {"MESOPOTAMIA", "BABYLONIANS", "HIEROGLYPHS", "SARCOPHAGUS", "ZIGGURATS", "CUNEIFORMS", "ARCHAEOLOGY", "INSCRIPTION", "CENTURIONS", "GLADIATORS", "CUNEIFORM", "AQUEDUCTS"}
    },
    {
        "Neurobiology",
        {"NEUROTRANSM", "SYNAPSES", "CEREBELLUM", "HIPPOCAMPUS", "NEUROGENES", "MYELINATION", "DENDRITES", "CORTICAL", "AXONALPATH", "BRAINSTEMS", "NEUROPATHY", "PLASTICITY"}
    },
    {
        "Classical Mythology",
        {"PROMETHEUS", "EPIMETHEUS", "BELLEROPHON", "ANDROMEDA", "LABYRINTHS", "PERSEPHONE", "MINOTAURS", "POLYPHEMUS", "MYTHOLOGIES", "HEPHAESTUS", "AGAMEMNON", "HERCULEAN"}
    },
    {
        "World Literature",
        {"PROTAGONIST", "ANTAGONISTS", "METAPHORIC", "SOLILOQUY", "NARRATIVES", "LITERATURE", "EPICPOETRY", "DRAMATURGY", "SYMBOLICAL", "FORESHADOW", "ALLEGORICAL", "HYPERBOLE"}
    },
    {
        "Maritime History",
        {"DREADNOUGHT", "CIRCUMNAVIG", "PRIVATEERS", "BATTLESHIPS", "BUCCANEERS", "NAVIGATION", "QUARTERDECK", "FLAGSHIPS", "MERCHANTMAN", "ADMIRALTY", "SEAFARERS", "FRIGATES"}
    },
    {
        "Volcanology",
        {"PYROCLASTIC", "STRATOVOLCA", "CALDERAS", "VOLCANOLOGY", "TEPHRADUST", "MAGMAFLUID", "GEOTHERMALS", "FUMAROLES", "SEISMOLOGY", "SUPERVOLCAN", "IGNIMBRITE", "BASALTICLAV"}
    },
    {
        "Botany & Taxonomy",
        {"ANGIOSPERMS", "GYMNOSPERMS", "CHLOROPHYLL", "PHOTOSYNTH", "DICOTYLEDON", "HERBARIUMS", "TAXONOMICAL", "INFLORESCEN", "POLLINATION", "GERMINATION", "BRYOPHYTES", "PTERIDOPHYT"}
    },
    {
        "Architecture Styles",
        {"BRUTALISTIC", "NEOGOTHIC", "BAROQUENESS", "NEOCLASSIC", "CANTILEVERS", "COLONNADES", "FLYINGBUTTR", "CLEARSTORY", "ARCHITECTUR", "ROMANESQUE", "DECONSTRUCT", "ARTNOUVEAU"}
    },
    {
        "Modern Philosophy",
        {"EPISTEMOLOG", "EXISTENTIAL", "PHILOSOPHIC", "UTILITARIAN", "DETERMINISM", "METAPHYSICS", "EMPIRICISMS", "PHENOMENON", "CATEGORICAL", "RATIONALITY", "PRAGMATISMS", "ONTOLOGICAL"}
    },
    {
        "Culinary Techniques",
        {"CARAMELIZED", "FERMENTAT", "SOUSVIDEWAY", "EMULSIFYING", "CONFITING", "REDUCTIONS", "GASTRONOMY", "BRAISINGPAN", "FLAMBEING", "MACERATION", "PASTEURIZE", "BLANCHING"}
    },
    {
        "Geomorphology",
        {"SEDIMENTARY", "ALLUVIALFAN", "DENUDATION", "PALEOGEOGRA", "CONTINENTAL", "METAMORPHIC", "STRATIGRAPH", "WEATHERINGS", "FAULTLINES", "GEOMORPHOLO", "OROGENESIS", "TECTONICS"}
    },
    {
        "Entomology",
        {"METAMORPHOS", "EXOSKELETON", "ENTOMOLOGY", "COLEOPTERA", "LEPIDOPTERA", "PROBOSCIS", "MANDIBLES", "CHRYSALISES", "ARTHROPODS", "PHEROMONES", "CARAPACES", "SUBTERRANE"}
    },
    {
        "Linguistics",
        {"MORPHOLOGY", "PHONOLOGY", "SYNTACTICAL", "SEMANTICAL", "ETYMOLOGY", "ORTHOGRAPHY", "DIALECTICAL", "CONSONANTS", "DIPHTHONGS", "LINGUISTICS", "LEXICOGRAPH", "VOCABULARY"}
    },
    {
        "Microbiology",
        {"BACTERIOPH", "ANTIBIOTICS", "PROKARYOTES", "EUKARYOTES", "MICROSCOPES", "PETRIDISHES", "PATHOGENIC", "ENDOSPORES", "STAPHYLOCOC", "MICROBIAL", "MEMBRANOUS", "ORGANISMS"}
    },
    {
        "Medieval Warfare",
        {"SIEGETOWERS", "BROADSWORDS", "BATTLEFIELD", "CHAINMAILS", "CROSSBOWMEN", "BARRICADES", "STRONGHOLDS", "WARHAMMERS", "MOUNTEDKNIG", "PROVISIONS", "CATAPULTS", "LONGBOWMAN"}
    },
    {
        "Cinematic Arts",
        {"CINEMATOGRA", "SCREENPLAY", "STORYBOARDS", "POSTPRODUCT", "SOUNDTRACKS", "COMPOSITORS", "EXECUTIVEPR", "FILMMAKERS", "RETROSPECTI", "DOCUMENTARY", "CHOREOGRAPH", "ANIMATIONS"}
    },
    {
        "Space Exploration",
        {"TRANSLUNARS", "SPACECRAFTS", "LUNARMODULE", "COSMONAUTS", "ASTRONAUTIC", "PROPULSIONS", "LAUNCHPADS", "SPACEPROBES", "DOCKINGBAYS", "GRAVITATION", "ROCKETSHIPS", "MISSIONCTRL"}
    },
    {
        "Meteorological Wonders",
        {"AURORABOREA", "WATERSPOUTS", "THUNDERHEAD", "SUPERCELLS", "TORNADOES", "HURRICANES", "LIGHTNINGS", "DOWNBURSTS", "WHITEOUTS", "MONSOONAL", "STRATOCUMUL", "SNOWSQUALLS"}
    },
    {
        "Cartography",
        {"MERCATORWAY", "EQUATORIALS", "TOPOGRAPHIC", "LATITUDES", "LONGITUDES", "CARTOGRAPHY", "HEMISPHERES", "COORDINATES", "NAVIGATIONS", "ELEVATIONS", "PRINCMERIDI", "ORIENTEER"}
    },
    {
        "Musical Mastery",
        {"PHILHARMONI", "HARPSICHORD", "POLYPHONIC", "TIMPANIROLL", "ORCHESTRATE", "COMPOSITION", "CONCERTMEIS", "DISCORDANCE", "PERCUSSION", "CONDUCTORS", "IMPROVISATO", "REPERTOIRES"}
    },
    {
        "Glaciology",
        {"CALVINGZONE", "SERACFALLS", "PERMAFROSTS", "GLACIATIONS", "ICEBERGFALL", "MORAINEBANK", "SUBGLACIAL", "FIRNFIELDS", "GLACIOLOGIC", "CREVASSING", "POLARCAPS", "ACCUMULAT"}
    },
    {
        "Horology Science",
        {"ESCAPEMENTS", "TOURBILLONS", "CHRONOGRAPH", "HOROLOGICAL", "TIMEKEEPING", "PENDULUMS", "MAINSPRINGS", "MECHANISMS", "OSCILLATION", "CHRONOMETER", "REGULATORS", "QUARTZCLOCK"}
    },
    {
        "Marine Ecology",
        {"BIODIVERSE", "PHYTOPLANKT", "ZOOPLANKTON", "CONSERVAT", "MANGROVES", "ESTUARINES", "INTERTIDAL", "OVERFISHING", "AQUACULTURE", "BIOMASSES", "CORALBLEACH", "HABITATIONS"}
    },
    {
        "Optics & Light",
        {"REFRACTIONS", "DIFFRACTION", "INTERFERENC", "POLARIZAT", "SPECTROMETE", "CHROMATICS", "PHOTONICS", "LUMINESCENC", "ILLUMINAT", "MAGNIFYING", "REFLECTION", "OPTICALLENS"}
    },
    {
        "Genetics & DNA",
        {"CHROMOSOMES", "DOUBLEHELIX", "NUCLEOTIDES", "MUTAGENESIS", "REPLICATION", "GENOMICSYS", "EPIGENETICS", "SEQUENCINGS", "INHERITANCE", "POLYPEPTIDE", "TRANSCRIPT", "TRANSLATION"}
    },
    {
        "Acoustics & Sound",
        {"FREQUENCIES", "REVERBERAT", "RESONANCES", "DECIBELMTR", "ULTRASONIC", "WAVELENGTHS", "INFRASONIC", "HARMONICAL", "AMPLITUDES", "DIFFUSIONS", "TRANSDUCERS", "ACOUSTICAL"}
    },
    {
        "Forestry Management",
        {"REFORESTAT", "SILVICULTUR", "ARBORICULT", "TIMBERLANDS", "DEFORESTAT", "PRESCRIBED", "OVERSTORYS", "UNDERSTOR", "AFFORESTAT", "SUSTAINABLE", "ECOSYSTEMIC", "WILDLANDS"}
    },
    {
        "Metallurgy",
        {"BLASTFURN", "ANNEALINGS", "FORGINGSYS", "TEMPERINGS", "METALLURGIC", "ALLOYSTEELS", "HARDENINGS", "GALVANIZING", "EXTRUSIONS", "CASTINGMOLD", "FOUNDRYWORK", "SMELTING"}
    },
    {
        "Ancient Rome",
        {"COLOSSEUMS", "GLADIATORS", "CENTURIONS", "LEGIONNAIRE", "PATRICIANS", "PRAETORIANS", "AQUEDUCTAL", "TRIUMPHALAR", "CONSULATES", "REPUBLICAN", "PROCONSULS", "IMPERATORS"}
    },
    {
        "Ornithology",
        {"PLUMAGETYPE", "MIGRATIONAL", "ORNITHOLOGY", "INCUBATIONS", "PASSERINES", "CARNIVOROUS", "AVIANSPECI", "TERRITORIES", "PREENINGS", "CLUTCHES", "REPRODUCTIV", "NEOPHOTICS"}
    },
    {
        "Theoretical Physics",
        {"STRINGTHEOR", "RELATIVITY", "QUANTUMMECH", "SINGULARITY", "PARTICLEPHY", "ENTANGLEMEN", "SUPERSYMMET", "SPACETIMES", "GRAVITONS", "HADRONCOLLI", "THEORETICAL", "HIGGSBOSON"}
    },
    {
        "Desert Landscapes",
        {"BADLANDSREG", "WINDEROSION", "PLAYALAKES", "SANDSTONES", "INSELBERGS", "SLOTCANVONS", "ARROYOWAYS", "DESERTIFICA", "MESAFORMAT", "BUTTEPEAKS", "EOLIANROCKS", "ALLUVIALS"}
    },
    {
        "Printmaking",
        {"WOODBLOCKS", "MEZZOTINTS", "LITHOGRAPHY", "INTAGLIOART", "SERIGRAPHIC", "AQUATINTS", "MONOTYPING", "ENGRAVINGS", "PRINTMAKERS", "IMPRESSIONS", "DRYPOINTING", "TYPOGRAPHY"}
    },
    {
        "Wilderness Survival",
        {"BUSHCRAFTER", "SHELTERWORK", "NAVIGATION", "FIRESTARTER", "PURIFICAT", "FORAGINGWAY", "TOURNIQUETS", "ORIENTEER", "FIRSTAIDKIT", "PROVISIONS", "WILDERNESS", "TOPOGRAPHIC"}
    },
    {
        "Deep Ocean Trenches",
        {"MARIANATRN", "HADALZONES", "BATHYPELAGI", "DEEPSEAVENT", "SUBDUCTION", "BAROPHILES", "BENTHOSWAYS", "CHEMOSYNTH", "BIOLUMINESC", "GIGANTISMS", "PRESSURIZED", "ABYSSOPELAG"}
    },
    {
        "Historical Expeditions",
        {"EXPEDITIONS", "CIRCUMNAVIG", "EXPLORATION", "DISCOVERIES", "TRANSOCEAN", "VOYAGEURWAY", "CARTOGRAPHE", "PATHFINDERS", "HISTORICAL", "NORTHWESTPA", "CONQUISTAD", "ADVENTURERS"}
    },
    {
        "Prehistoric Mammals",
        {"WOOLLYMAMMO", "MASTODONS", "SABERTOOTHS", "MEGATHERIUM", "GLYPTODONTS", "PLEISTOCENE", "HERBIVOROUS", "FOSSILIFERO", "PREHISTORIC", "TERATORNBIR", "CARNIVOROUS", "NEANDERTHAL"}
    },
    {
        "Biochemistry",
        {"METABOLISMS", "AMINOACIDIC", "GLYCOLYSIS", "MITOCHONDRI", "POLYPEPTIDE", "BIOSYNTHESI", "NUCLEICACID", "CATALYSIS", "BIOCHEMICAL", "PHOSPHATE", "RESPIRATION", "COENZYMES"}
    },
    {
        "Epic Poetry",
        {"HOMERICHERO", "ALLITERATIV", "DIBACCHELIC", "HEXAMETERS", "INMEDIASRES", "EPITROPICAL", "APOSTROPHE", "INVOCATION", "LEGENDARIES", "RHAPSODISTS", "MYTHICWARS", "STROPHES"}
    },
    {
        "Subterranean Caves",
        {"STALACTITES", "STALAGMITES", "SPELEOTHEMS", "CAVERNICOLO", "SPELUNKING", "FLOWSTONES", "TROGLOBITES", "SUBTERRANE", "KARSTLANDSC", "SINKHOLESYS", "UNDERGROUND", "LIMESTONES"}
    },
    {
        "Ecology & Biomes",
        {"CONSERVAT", "BIOSPHERE", "BIODIVERSE", "RAINFORESTS", "SUSTAINABLE", "SAVANNAHLAN", "PERMAFROSTS", "ECOLOGICAL", "FOODCHAINS", "POPULATION", "HABITATLOSS", "ECOSYSTEMS"}
    },
    {
        "Space Robotics",
        {"AUTONOMOUS", "ROBOTICARMS", "ROVERWHEELS", "TELEMETRIES", "SOLARPANELS", "COMMUNICAT", "ALGORITHMIC", "SPACEPROBES", "SAMPLECACHE", "LANDERSYSTE", "MICROCONTRO", "SERVOMOTORS"}
    },
    {
        "Renaissance Philosophy",
        {"HUMANISMWAY", "NEOPLATONIS", "INDIVIDUALI", "SECULARISMS", "RENAISSANCE", "REFORMATION", "SCHOLASTIC", "RATIONALITY", "VERNACULAR", "INTELLECTUA", "PHILOSOPHER", "ENLIGHTENED"}
    },
    {
        "Weather Extremes",
        {"MICROBURSTS", "HEATWAVINGS", "FREEZINGRAI", "COLDFRONTS", "DUSTDEVILS", "THUNDERST", "HABOOBLIGHT", "ATMOSPHERIC", "BAROMETRICS", "MONSOONINGS", "SUPERCELLAR", "CLOUDBURSTS"}
    },
};


inline const ThemeDef* getWordSearchPool(WordSearchDifficulty diff, size_t& outCount) {
    outCount = NUM_WS_THEMES_PER_DIFF;
    switch (diff) {
        case WS_EASY:
            return EASY_THEMES;
        case WS_HARD:
            return HARD_THEMES;
        case WS_MEDIUM:
        default:
            return MEDIUM_THEMES;
    }
}

#endif // WORD_SEARCH_DATASET_H
