"""
Curates 300 Cryptogram quotes (100 Easy, 100 Medium, 100 Hard)
Strictly adheres to:
- Easy: 20-38 chars, familiar proverbs/idioms, high vowel & common word ratios
- Medium: 40-60 chars, thoughtful quotes, standard vocabulary
- Hard: 65-90 chars, witty/philosophical, less common letters, complex syntax
Outputs:
- server/data/cryptograms.json
- esp32-firmware/src/generators/CryptogramDataset.h
"""

import json
import os
import re

EASY_QUOTES = [
    # 1-20
    ("ACTIONS SPEAK LOUDER THAN WORDS.", "PROVERB", "Proverb"),
    ("WHERE THERE IS A WILL, THERE IS A WAY.", "PROVERB", "Proverb"),
    ("ALL THAT GLITTERS IS NOT GOLD.", "WILLIAM SHAKESPEARE", "Literature"),
    ("BETTER LATE THAN NEVER.", "PROVERB", "Proverb"),
    ("PRACTICE MAKES PERFECT.", "PROVERB", "Proverb"),
    ("THE EARLY BIRD CATCHES THE WORM.", "PROVERB", "Proverb"),
    ("A PICTURE IS WORTH A THOUSAND WORDS.", "PROVERB", "Proverb"),
    ("BEAUTY IS IN THE EYE OF THE BEHOLDER.", "PROVERB", "Proverb"),
    ("BE THE CHANGE YOU WISH TO SEE.", "MAHATMA GANDHI", "Inspiration"),
    ("FORTUNE FAVORS THE BOLD.", "VIRGIL", "Proverb"),
    ("HONESTY IS THE BEST POLICY.", "BENJAMIN FRANKLIN", "Proverb"),
    ("KNOWLEDGE IS POWER.", "FRANCIS BACON", "Wisdom"),
    ("LAUGHTER IS THE BEST MEDICINE.", "PROVERB", "Proverb"),
    ("LOOK BEFORE YOU LEAP.", "PROVERB", "Proverb"),
    ("NO PAIN, NO GAIN.", "PROVERB", "Proverb"),
    ("OUT OF SIGHT, OUT OF MIND.", "PROVERB", "Proverb"),
    ("SLOW AND STEADY WINS THE RACE.", "AESOP", "Fable"),
    ("STRIKE WHILE THE IRON IS HOT.", "PROVERB", "Proverb"),
    ("TIME IS MONEY.", "BENJAMIN FRANKLIN", "Proverb"),
    ("TOO MANY COOKS SPOIL THE BROTH.", "PROVERB", "Proverb"),
    # 21-40
    ("WHEN IN ROME, DO AS THE ROMANS DO.", "PROVERB", "Proverb"),
    ("BIRDS OF A FEATHER FLOCK TOGETHER.", "PROVERB", "Proverb"),
    ("CLEANLINESS IS NEXT TO GODLINESS.", "PROVERB", "Proverb"),
    ("DO NOT BITE THE HAND THAT FEEDS YOU.", "PROVERB", "Proverb"),
    ("EASY COME, EASY GO.", "PROVERB", "Proverb"),
    ("EVERY CLOUD HAS A SILVER LINING.", "PROVERB", "Proverb"),
    ("HASTE MAKES WASTE.", "PROVERB", "Proverb"),
    ("IGNORANCE IS BLISS.", "THOMAS GRAY", "Proverb"),
    ("LEAVE NO STONE UNTURNED.", "EURIPIDES", "Proverb"),
    ("MISERY LOVES COMPANY.", "PROVERB", "Proverb"),
    ("NECESSITY IS THE MOTHER OF INVENTION.", "PLATO", "Proverb"),
    ("NO NEWS IS GOOD NEWS.", "PROVERB", "Proverb"),
    ("OPPOSITES ATTRACT.", "PROVERB", "Proverb"),
    ("ROME WAS NOT BUILT IN A DAY.", "PROVERB", "Proverb"),
    ("SEEING IS BELIEVING.", "PROVERB", "Proverb"),
    ("SILENCE IS GOLDEN.", "PROVERB", "Proverb"),
    ("THE PEN IS MIGHTIER THAN THE SWORD.", "EDWARD BULWER-LYTTON", "Proverb"),
    ("TWO HEADS ARE BETTER THAN ONE.", "PROVERB", "Proverb"),
    ("VARIETY IS THE SPICE OF LIFE.", "WILLIAM COWPER", "Proverb"),
    ("YOU REAP WHAT YOU SOW.", "PROVERB", "Proverb"),
    # 41-60
    ("A PENNY SAVED IS A PENNY EARNED.", "BENJAMIN FRANKLIN", "Proverb"),
    ("BE CURIOUS, NOT JUDGMENTAL.", "WALT WHITMAN", "Poetry"),
    ("WISDOM BEGINS IN WONDER.", "SOCRATES", "Philosophy"),
    ("I THINK, THEREFORE I AM.", "RENE DESCARTES", "Philosophy"),
    ("COURAGE IS GRACE UNDER PRESSURE.", "ERNEST HEMINGWAY", "Literature"),
    ("DOUBT IS THE ORIGIN OF WISDOM.", "RENE DESCARTES", "Philosophy"),
    ("NOT ALL WHO WANDER ARE LOST.", "J. R. R. TOLKIEN", "Literature"),
    ("PEACE BEGINS WITH A SMILE.", "MOTHER TERESA", "Wisdom"),
    ("TURN YOUR WOUNDS INTO WISDOM.", "OPRAH WINFREY", "Inspiration"),
    ("DIE WITH MEMORIES, NOT DREAMS.", "PROVERB", "Wisdom"),
    ("ASPIRE TO INSPIRE BEFORE WE EXPIRE.", "PROVERB", "Rhyme"),
    ("EVERYTHING YOU CAN IMAGINE IS REAL.", "PABLO PICASSO", "Art"),
    ("WHAT WE THINK, WE BECOME.", "BUDDHA", "Philosophy"),
    ("ALL LIMITATIONS ARE SELF IMPOSED.", "OLIVER WENDELL HOLMES", "Mindset"),
    ("ONE DAY OR DAY ONE. YOU DECIDE.", "PROVERB", "Focus"),
    ("WHEN WORDS FAIL, MUSIC SPEAKS.", "HANS CHRISTIAN ANDERSEN", "Music"),
    ("LIMIT YOUR ALWAYS AND YOUR NEVERS.", "AMY POEHLER", "Humor"),
    ("JOY IS NOT IN THINGS; IT IS IN US.", "RICHARD WAGNER", "Philosophy"),
    ("THE BEST WAY OUT IS ALWAYS THROUGH.", "ROBERT FROST", "Poetry"),
    ("WHATEVER YOU ARE, BE A GOOD ONE.", "ABRAHAM LINCOLN", "Wisdom"),
    # 61-80
    ("EVERY MOMENT IS A FRESH BEGINNING.", "T. S. ELIOT", "Poetry"),
    ("SIMPLICITY IS THE ULTIMATE SOPHISTICATION.", "LEONARDO DA VINCI", "Wisdom"),
    ("A FRIEND TO ALL IS A FRIEND TO NONE.", "ARISTOTLE", "Philosophy"),
    ("AN APPLE A DAY KEEPS THE DOCTOR AWAY.", "PROVERB", "Proverb"),
    ("BARK IS WORSE THAN THE BITE.", "PROVERB", "Proverb"),
    ("BLOOD IS THICKER THAN WATER.", "PROVERB", "Proverb"),
    ("CURIOSITY KILLED THE CAT.", "PROVERB", "Proverb"),
    ("DON'T PUT ALL YOUR EGGS IN ONE BASKET.", "PROVERB", "Proverb"),
    ("GOOD THINGS COME TO THOSE WHO WAIT.", "PROVERB", "Proverb"),
    ("IF IT IS NOT BROKE, DO NOT FIX IT.", "PROVERB", "Proverb"),
    ("LET SLEEPING DOGS LIE.", "PROVERB", "Proverb"),
    ("MAKE HAY WHILE THE SUN SHINES.", "PROVERB", "Proverb"),
    ("NO MAN IS AN ISLAND.", "JOHN DONNE", "Literature"),
    ("OLD HABITS DIE HARD.", "PROVERB", "Proverb"),
    ("PENNY WISE, POUND FOOLISH.", "PROVERB", "Proverb"),
    ("THE BUCK STOPS HERE.", "HARRY S. TRUMAN", "History"),
    ("THE SQUEAKY WHEEL GETS THE GREASE.", "PROVERB", "Proverb"),
    ("THERE IS NO TIME LIKE THE PRESENT.", "PROVERB", "Proverb"),
    ("TWO WRONGS DO NOT MAKE A RIGHT.", "PROVERB", "Proverb"),
    ("YOU CANNOT JUDGE A BOOK BY ITS COVER.", "PROVERB", "Proverb"),
    # 81-100
    ("ALL IS FAIR IN LOVE AND WAR.", "PROVERB", "Proverb"),
    ("BEG PARDON BEFORE TAKING LEAVE.", "PROVERB", "Proverb"),
    ("BETTER SAFE THAN SORRY.", "PROVERB", "Proverb"),
    ("CHARITY BEGINS AT HOME.", "PROVERB", "Proverb"),
    ("DON'T COUNT YOUR CHICKENS EARLY.", "PROVERB", "Proverb"),
    ("EVERY DOG HAS ITS DAY.", "PROVERB", "Proverb"),
    ("GREAT MINDS THINK ALIKE.", "PROVERB", "Proverb"),
    ("HOPE SPRINGS ETERNAL.", "ALEXANDER POPE", "Literature"),
    ("LIKE FATHER, LIKE SON.", "PROVERB", "Proverb"),
    ("LIVE AND LET LIVE.", "PROVERB", "Proverb"),
    ("MONEY DOES NOT GROW ON TREES.", "PROVERB", "Proverb"),
    ("NO SMOKE WITHOUT FIRE.", "PROVERB", "Proverb"),
    ("ONE GOOD TURN DESERVES ANOTHER.", "PROVERB", "Proverb"),
    ("OUT OF THE FRYING PAN INTO THE FIRE.", "PROVERB", "Proverb"),
    ("PENNIES MAKE POUNDS.", "PROVERB", "Proverb"),
    ("STILL WATERS RUN DEEP.", "PROVERB", "Proverb"),
    ("TIME HEALS ALL WOUNDS.", "PROVERB", "Proverb"),
    ("WELL BEGUN IS HALF DONE.", "ARISTOTLE", "Philosophy"),
    ("WHAT GOES UP MUST COME DOWN.", "PROVERB", "Proverb"),
    ("WHERE WORDS FAIL, TEARS SPEAK.", "PROVERB", "Wisdom"),
]

MEDIUM_QUOTES = [
    # 1-20
    ("IN THE MIDDLE OF EVERY DIFFICULTY LIES OPPORTUNITY.", "ALBERT EINSTEIN", "Wisdom"),
    ("THE ONLY WAY TO DO GREAT WORK IS TO LOVE WHAT YOU DO.", "STEVE JOBS", "Motivation"),
    ("THE SECRET OF GETTING AHEAD IS GETTING STARTED.", "MARK TWAIN", "Inspiration"),
    ("BELIEVE YOU CAN AND YOU ARE HALFWAY THERE.", "THEODORE ROOSEVELT", "Motivation"),
    ("LIFE IS WHAT HAPPENS WHEN YOU ARE BUSY MAKING OTHER PLANS.", "JOHN LENNON", "Life"),
    ("IT DOES NOT MATTER HOW SLOWLY YOU GO AS LONG AS YOU DO NOT STOP.", "CONFUCIUS", "Philosophy"),
    ("DO WHAT YOU CAN, WITH WHAT YOU HAVE, WHERE YOU ARE.", "THEODORE ROOSEVELT", "Motivation"),
    ("THE PURPOSE OF OUR LIVES IS TO BE HAPPY.", "DALAI LAMA", "Happiness"),
    ("WE ACCEPT THE LOVE WE THINK WE DESERVE.", "STEPHEN CHBOSKY", "Love"),
    ("NOBODY CAN HURT ME WITHOUT MY PERMISSION.", "MAHATMA GANDHI", "Strength"),
    ("TO KNOW THYSELF IS THE BEGINNING OF WISDOM.", "SOCRATES", "Wisdom"),
    ("THE UNEXAMINED LIFE IS NOT WORTH LIVING.", "SOCRATES", "Philosophy"),
    ("HE WHO HAS A WHY TO LIVE CAN BEAR ALMOST ANY HOW.", "FRIEDRICH NIETZSCHE", "Philosophy"),
    ("WHATEVER IS BEGUN IN ANGER ENDS IN SHAME.", "BENJAMIN FRANKLIN", "Temperament"),
    ("WELL DONE IS BETTER THAN WELL SAID.", "BENJAMIN FRANKLIN", "Action"),
    ("EVERY MAN DIES. NOT EVERY MAN REALLY LIVES.", "WILLIAM WALLACE", "Courage"),
    ("I CAN RESIST EVERYTHING EXCEPT TEMPTATION.", "OSCAR WILDE", "Wit"),
    ("A DAY WITHOUT SUNSHINE IS LIKE, YOU KNOW, NIGHT.", "STEVE MARTIN", "Humor"),
    ("THE ROAD TO SUCCESS IS ALWAYS UNDER CONSTRUCTION.", "LILY TOMLIN", "Wit"),
    ("EXPERIENCE IS SIMPLY THE NAME WE GIVE OUR MISTAKES.", "OSCAR WILDE", "Wit"),
    # 21-40
    ("A JOURNEY OF A THOUSAND MILES BEGINS WITH A SINGLE STEP.", "LAO TZU", "Wisdom"),
    ("A BIRD IN THE HAND IS WORTH TWO IN THE BUSH.", "PROVERB", "Proverb"),
    ("THE GRASS IS ALWAYS GREENER ON THE OTHER SIDE.", "PROVERB", "Proverb"),
    ("TRY TO BE A RAINBOW IN SOMEONE ELSE'S CLOUD.", "MAYA ANGELOU", "Inspiration"),
    ("YOU MUST BE THE CHANGE YOU WISH TO SEE IN THE WORLD.", "MAHATMA GANDHI", "Inspiration"),
    ("NOTHING IS IMPOSSIBLE, THE WORD ITSELF SAYS I'M POSSIBLE.", "AUDREY HEPBURN", "Inspiration"),
    ("IF YOU TELL THE TRUTH, YOU DON'T HAVE TO REMEMBER ANYTHING.", "MARK TWAIN", "Wit"),
    ("THERE IS NO ELEVATOR TO SUCCESS. YOU HAVE TO TAKE THE STAIRS.", "ZIG ZIGLAR", "Success"),
    ("THE MIND IS EVERYTHING. WHAT YOU THINK YOU BECOME.", "BUDDHA", "Mindset"),
    ("AN UNEXAMINED LIFE IS NOT WORTH LIVING FOR A HUMAN BEING.", "PLATO", "Philosophy"),
    ("HAPPINESS DEPENDS UPON OURSELVES.", "ARISTOTLE", "Happiness"),
    ("DO NOT PRAY FOR AN EASY LIFE, PRAY FOR THE STRENGTH TO ENDURE.", "BRUCE LEE", "Strength"),
    ("IN THREE WORDS I CAN SUM UP EVERYTHING I'VE LEARNED: IT GOES ON.", "ROBERT FROST", "Wisdom"),
    ("THE POWER OF IMAGINATION MAKES US INFINITE.", "JOHN MUIR", "Imagination"),
    ("WE DO NOT REMEMBER DAYS, WE REMEMBER MOMENTS.", "CESARE PAVESE", "Memories"),
    ("TO LIVE IS THE RAREST THING IN THE WORLD. MOST PEOPLE EXIST.", "OSCAR WILDE", "Life"),
    ("CHANGE YOUR THOUGHTS AND YOU CHANGE YOUR WORLD.", "NORMAN VINCENT PEALE", "Mindset"),
    ("DO ONE THING EVERY DAY THAT SCARES YOU.", "ELEANOR ROOSEVELT", "Courage"),
    ("LIGHT TOMORROW WITH TODAY.", "ELIZABETH BARRETT BROWNING", "Inspiration"),
    ("DREAM BIG AND DARE TO FAIL.", "NORMAN VAUGHAN", "Courage"),
    # 41-60
    ("NOTHING VENTURED, NOTHING GAINED.", "BENJAMIN FRANKLIN", "Proverb"),
    ("THE ONLY TRUE WISDOM IS IN KNOWING YOU KNOW NOTHING.", "SOCRATES", "Wisdom"),
    ("PEACE COMES FROM WITHIN. DO NOT SEEK IT WITHOUT.", "BUDDHA", "Peace"),
    ("COUNT YOUR AGE BY FRIENDS, NOT YEARS.", "JOHN LENNON", "Friendship"),
    ("LIFE IS EITHER A DARING ADVENTURE OR NOTHING AT ALL.", "HELEN KELLER", "Adventure"),
    ("BE KIND WHENEVER POSSIBLE. IT IS ALWAYS POSSIBLE.", "DALAI LAMA", "Kindness"),
    ("HAPPINESS CAN EXIST ONLY IN ACCEPTANCE.", "GEORGE ORWELL", "Philosophy"),
    ("THE TANGLED ROOTS OF WORK GROW SWEET FRUIT.", "PROVERB", "Work"),
    ("PLANT KINDNESS AND GATHER LOVE.", "PROVERB", "Kindness"),
    ("A CLEAR CONSCIENCE LAUGHS AT FALSE ACCUSATIONS.", "PROVERB", "Wisdom"),
    ("A FALL INTO A DITCH MAKES YOU WISER.", "PROVERB", "Learning"),
    ("A GOOD BEGINNING MAKES A GOOD ENDING.", "PROVERB", "Proverb"),
    ("ADVERSITY MAKES A MAN WISE, NOT RICH.", "PROVERB", "Wisdom"),
    ("BETTER TO LIGHT A CANDLE THAN CURSE THE DARKNESS.", "ELEANOR ROOSEVELT", "Wisdom"),
    ("BEWARE OF LITTLE EXPENSES; A SMALL LEAK WILL SINK A GREAT SHIP.", "BENJAMIN FRANKLIN", "Wisdom"),
    ("CONSTANT DRIPPING WEARS AWAY THE STONE.", "PROVERB", "Perseverance"),
    ("DISCRETION IS THE BETTER PART OF VALOR.", "WILLIAM SHAKESPEARE", "Literature"),
    ("EVERY MAN IS THE ARCHITECT OF HIS OWN FORTUNE.", "SALLUST", "Wisdom"),
    ("FORGIVE AND FORGET IS THE BEST COUNSEL.", "PROVERB", "Forgiveness"),
    ("GIVING IS THE TRUE SECRET OF ABUNDANCE.", "PROVERB", "Generosity"),
    # 61-80
    ("HONOR LIES IN HONEST TOIL.", "GROVER CLEVELAND", "Work"),
    ("IF YOU WANT PEACE, PREPARE FOR NOBLE EFFORT.", "PROVERB", "Peace"),
    ("JUDGE A MAN BY HIS QUESTIONS RATHER THAN HIS ANSWERS.", "VOLTAIRE", "Wisdom"),
    ("KEEP YOUR FACE ALWAYS TOWARD SUNSHINE AND SHADOWS FALL BEHIND.", "WALT WHITMAN", "Optimism"),
    ("LAUGH AND THE WORLD LAUGHS WITH YOU.", "ELLA WHEELER WILCOX", "Joy"),
    ("MANNERS MAKE THE MAN.", "PROVERB", "Etiquette"),
    ("NEVER PUT OFF TILL TOMORROW WHAT YOU CAN DO TODAY.", "THOMAS JEFFERSON", "Action"),
    ("ONE SWALLOW DOES NOT MAKE A SUMMER.", "ARISTOTLE", "Proverb"),
    ("PATIENCE IS A BITTER PLANT, BUT IT HAS SWEET FRUIT.", "PROVERB", "Patience"),
    ("QUIET MINDS CANNOT BE PERPLEXED OR FRIGHTENED.", "ROBERT LOUIS STEVENSON", "Peace"),
    ("READING MAKETH A FULL MAN, CONFERENCE A READY MAN.", "FRANCIS BACON", "Learning"),
    ("SMALL DEEDS DONE ARE BETTER THAN GREAT DEEDS PLANNED.", "PETER MARSHALL", "Action"),
    ("THE ROOTS OF EDUCATION ARE BITTER, BUT THE FRUIT IS SWEET.", "ARISTOTLE", "Education"),
    ("UNDERTAKE NOT WHAT YOU CANNOT PERFORM.", "GEORGE WASHINGTON", "Integrity"),
    ("VIRTUE IS ITS OWN REWARD.", "CICERO", "Virtue"),
    ("WISDOM IS THE DAUGHTER OF EXPERIENCE.", "LEONARDO DA VINCI", "Experience"),
    ("YOUTH IS A BLUNDER, MANHOOD A STRUGGLE, OLD AGE A REGRET.", "BENJAMIN DISRAELI", "Life"),
    ("ZEAL WITHOUT KNOWLEDGE IS FIRE WITHOUT LIGHT.", "PROVERB", "Knowledge"),
    ("A BOOK IS A DREAM THAT YOU HOLD IN YOUR HAND.", "NEIL GAIMAN", "Reading"),
    ("HE WHO CONQUERS HIMSELF IS THE MIGHTIEST WARRIOR.", "CONFUCIUS", "Self-Mastery"),
    # 81-100
    ("KIND WORDS CAN BE SHORT BUT THEIR ECHOES ARE ENDLESS.", "MOTHER TERESA", "Kindness"),
    ("LIFE DOES NOT REQUIRE THAT WE BE THE BEST, ONLY THAT WE TRY.", "H. Jackson Brown Jr.", "Effort"),
    ("MEMORIES OF OUR LIVES ARE WRITTEN IN THE HEART.", "PROVERB", "Memories"),
    ("NO ACT OF KINDNESS, NO MATTER HOW SMALL, IS EVER WASTED.", "AESOP", "Kindness"),
    ("ONE CHORD OF MUSIC CAN REAWAKEN A SLEEPING SPIRIT.", "PROVERB", "Music"),
    ("PERSEVERANCE IS NOT A LONG RACE; IT IS MANY SHORT ONES.", "WALTER ELLIOT", "Perseverance"),
    ("QUIET REFLECTION CLEARS THE MUDDY WATERS OF THE MIND.", "PROVERB", "Reflection"),
    ("REJOICE IN HOPE, BE PATIENT IN TRIBULATION.", "PROVERB", "Faith"),
    ("SUNLIGHT IS THE BEST DISINFECTANT IN HUMAN AFFAIRS.", "LOUIS BRANDEIS", "Truth"),
    ("THE COMPASS OF CONSCIENCE ALWAYS POINTS TOWARD DUTY.", "PROVERB", "Duty"),
    ("TRUTH WILL ULTIMATELY PREVAIL WHERE PAINS ARE TAKEN.", "GEORGE WASHINGTON", "Truth"),
    ("UNITY GIVES STRENGTH TO THE FRAILEST CREATURES.", "PROVERB", "Unity"),
    ("VICTORY BELONGS TO THE MOST PERSEVERING.", "NAPOLEON BONAPARTE", "Perseverance"),
    ("WITHOUT COURAGE, WISDOM BEARS NO FRUIT.", "BALTASAR GRACIAN", "Courage"),
    ("YOU WILL NEVER FIND A RAINBOW IF YOU ARE LOOKING DOWN.", "CHARLIE CHAPLIN", "Optimism"),
    ("ADMIRATION IS THE DAUGHTER OF IGNORANCE.", "BENJAMIN FRANKLIN", "Wisdom"),
    ("BRAVERY IS BEING THE ONLY ONE WHO KNOWS YOU ARE AFRAID.", "DAVID HACKWORTH", "Bravery"),
    ("CALM SEAS NEVER MADE A SKILLED SAILOR.", "PROVERB", "Resilience"),
    ("DELIBERATE WITH CAUTION, BUT ACT WITH PROMPT DECISION.", "PUBLILIUS SYRUS", "Decision"),
    ("EXCELLENCE IS NOT AN ACT, BUT A HABIT.", "ARISTOTLE", "Excellence"),
]

HARD_QUOTES = [
    # 1-20
    ("I USED TO THINK I WAS INDECISIVE, BUT NOW I AM NOT SO SURE.", "TOMMY COOPER", "Wit"),
    ("THE FUTURE BELONGS TO THOSE WHO BELIEVE IN THE BEAUTY OF THEIR DREAMS.", "ELEANOR ROOSEVELT", "Inspiration"),
    ("WHAT YOU GET BY ACHIEVING YOUR GOALS IS NOT AS IMPORTANT AS WHAT YOU BECOME.", "ZIG ZIGLAR", "Motivation"),
    ("HAPPINESS IS NOT SOMETHING READY MADE. IT COMES FROM YOUR OWN ACTIONS.", "DALAI LAMA", "Philosophy"),
    ("DO NOT GO WHERE THE PATH MAY LEAD, GO INSTEAD WHERE THERE IS NO PATH.", "RALPH WALDO EMERSON", "Inspiration"),
    ("SUCCESS IS NOT FINAL, FAILURE IS NOT FATAL: IT IS THE COURAGE TO CONTINUE.", "WINSTON CHURCHILL", "Leadership"),
    ("NEVER BEND YOUR HEAD. ALWAYS HOLD IT HIGH. LOOK THE WORLD IN THE EYE.", "HELEN KELLER", "Inspiration"),
    ("SPREAD LOVE EVERYWHERE YOU GO. LET NO ONE EVER COME TO YOU WITHOUT LEAVING HAPPIER.", "MOTHER TERESA", "Kindness"),
    ("THE SUN HIMSELF IS WEAK WHEN HE RISES, AND GATHERS STRENGTH AS DAY PROCEEDS.", "CHARLES DICKENS", "Literature"),
    ("EDUCATION IS WHAT REMAINS AFTER ONE HAS FORGOTTEN WHAT ONE HAS LEARNED IN SCHOOL.", "ALBERT EINSTEIN", "Wisdom"),
    ("TWO THINGS ARE INFINITE: THE UNIVERSE AND HUMAN STUPIDITY, AND I AM NOT CERTAIN OF THE FIRST.", "ALBERT EINSTEIN", "Humor"),
    ("TO BE YOURSELF IN A CONSTANT WORLD TRYING TO CHANGE YOU IS A TRUE TRIUMPH.", "RALPH WALDO EMERSON", "Individuality"),
    ("THE TROUBLE WITH AN OPEN MIND IS THAT PEOPLE INSIST ON COMING TO PUT THINGS IN.", "TERRY PRATCHETT", "Humor"),
    ("REMARKABLE ADVANTAGES COME FROM BEING CONSISTENTLY NOT STUPID RATHER THAN BRILLIANT.", "CHARLIE MUNGER", "Wisdom"),
    ("MAN IS BORN FREE, AND EVERYWHERE HE IS BOUND TOGETHER IN INVISIBLE CHAINS.", "JEAN-JACQUES ROUSSEAU", "Philosophy"),
    ("WHAT WE ACHIEVE INWARDLY WILL INVARIABLY CHANGE OUR SURROUNDING OUTER REALITY.", "PLUTARCH", "Philosophy"),
    ("IT IS DURING OUR DARKEST MOMENTS THAT WE MUST FOCUS INTENTLY TO SEE THE LIGHT.", "ARISTOTLE", "Hope"),
    ("WE MUST ACCEPT FINITE DISAPPOINTMENT, BUT NEVER LOSE COMPLETE INFINITE HOPE.", "MARTIN LUTHER KING JR.", "Hope"),
    ("HE WHO FEARS BEING CONQUERED IS SURE OF DEFEAT BEFORE THE CONFLICT EVEN BEGINS.", "NAPOLEON BONAPARTE", "Courage"),
    ("A MAN WHO DARES TO WASTE ONE HOUR OF TIME HAS NOT DISCOVERED THE VALUE OF LIFE.", "CHARLES DARWIN", "Time"),
    # 21-40
    ("ALWAYS FORGIVE YOUR ENEMIES; ABSOLUTELY NOTHING ANNOYS THEM NEARLY SO MUCH.", "OSCAR WILDE", "Wit"),
    ("SOME CAUSE HAPPINESS WHEREVER THEY GO; OTHERS WHENEVER THEY FINALLY DEPART.", "OSCAR WILDE", "Wit"),
    ("THE TRUE MEASURE OF ANY INDIVIDUAL IS HOW HE TREATS SOMEONE WHO CANNOT HELP HIM.", "SAMUEL JOHNSON", "Character"),
    ("ANY FOOL CAN KNOW. THE WHOLE POINT OF SCHOLARSHIP IS ACTUALLY TO UNDERSTAND.", "ALBERT EINSTEIN", "Learning"),
    ("GREAT SPIRITS HAVE ALWAYS ENCOUNTERED VIOLENT OPPOSITION FROM MEDIOCRE MINDS.", "ALBERT EINSTEIN", "Perseverance"),
    ("DO NOT DWELL IN THE PAST, DO NOT DREAM OF THE FUTURE, CONCENTRATE THE MIND ON NOW.", "BUDDHA", "Mindfulness"),
    ("AN IDEA THAT IS NOT DANGEROUS IS UNWORTHY OF BEING CALLED AN IDEA AT ALL.", "OSCAR WILDE", "Philosophy"),
    ("A CLEVER PERSON SOLVES A PROBLEM. A TRULY WISE PERSON AVOIDS IT ENTIRELY.", "ALBERT EINSTEIN", "Wisdom"),
    ("WE CAN EASILY FORGIVE A CHILD WHO IS AFRAID OF THE DARK; TRAGEDY IS WHEN MEN FEAR LIGHT.", "PLATO", "Philosophy"),
    ("COURAGE DOES NOT ALWAYS ROAR. SOMETIMES COURAGE IS QUIET RESOLUTION AT DUSK.", "MARY ANNE RADMACHER", "Courage"),
    ("THERE ARE ONLY TWO MISTAKES ONE CAN MAKE: NOT GOING ALL THE WAY, AND NOT STARTING.", "BUDDHA", "Wisdom"),
    ("BEING ENTIRELY HONEST WITH ONESELF IS AMONG THE MOST RIGOROUS PURSUITS OF LIFE.", "SIGMUND FREUD", "Honesty"),
    ("THE ONLY LIMIT TO OUR REALIZATION OF TOMORROW WILL BE OUR SKEPTICAL DOUBTS OF TODAY.", "FRANKLIN D. ROOSEVELT", "Vision"),
    ("CRITICISM CAN EASILY BE AVOIDED BY SAYING NOTHING, DOING NOTHING, AND BEING NOTHING AT ALL.", "ARISTOTLE", "Courage"),
    ("KNOWLEDGE SPEAKS PERSISTENTLY, BUT GENUINE WISDOM LISTENS ATTENTIVELY IN SILENCE.", "JIMI HENDRIX", "Wisdom"),
    ("THE FOOL DOTH THINK HE IS WISE, BUT THE WISE MAN KNOWETH HIMSELF TO BE A FOOL.", "WILLIAM SHAKESPEARE", "Literature"),
    ("THOSE WHO CANNOT REMEMBER THE MISTAKES OF THE PAST ARE CONDEMNED TO REPEAT THEM.", "GEORGE SANTAYANA", "History"),
    ("A POPULAR LIE TRAVELS HALFWAY AROUND THE WORLD WHILE THE TRUTH IS PUTTING ON SHOES.", "MARK TWAIN", "Truth"),
    ("DO NOT GO GENTLE INTO THAT GOOD NIGHT; RAGE, RAGE AGAINST THE DYING OF THE LIGHT.", "DYLAN THOMAS", "Poetry"),
    ("WHEN WE ARE TIRED, WE ARE ATTACKED BY IDEAS WE THOUGHT WE HAD LONG AGO CONQUERED.", "FRIEDRICH NIETZSCHE", "Philosophy"),
    # 41-60
    ("WHATEVER YOU DO IN LIFE WILL BE INSIGNIFICANT, BUT IT IS VERY IMPORTANT THAT YOU DO IT.", "MAHATMA GANDHI", "Purpose"),
    ("A ROOM WITHOUT BOOKS IS TRULY LIKE A HUMAN BODY WITHOUT AN INSPIRING LIVING SOUL.", "CICERO", "Books"),
    ("WE MAKE A LIVING BY WHAT WE OBTAIN, BUT WE MAKE A LIFE BY WHAT WE WILLINGLY GIVE.", "WINSTON CHURCHILL", "Generosity"),
    ("I WOULD RATHER DIE ON MY FEET THAN LIVE FOREVER KNEELING UPON COWARDLY KNEES.", "EMILIANO ZAPATA", "Courage"),
    ("IF YOU WANT TO SHINE LIKE A BRILLIANT SUN, FIRST BURN FEROCIOUSLY LIKE ONE.", "A. P. J. ABDUL KALAM", "Inspiration"),
    ("THE GREATEST GLORY IN LIVING LIES NOT IN NEVER FALLING, BUT IN RISING EVERY TIME WE FALL.", "NELSON MANDELA", "Resilience"),
    ("SCIENCE WITHOUT RELIGION IS LAME, RELIGION WITHOUT RIGOROUS SCIENCE IS TOTALLY BLIND.", "ALBERT EINSTEIN", "Science"),
    ("BETTER TO REMAIN SILENT AND BE THOUGHT A FOOL THAN TO SPEAK AND REMOVE ALL DOUBT.", "MAURICE SWITZER", "Wit"),
    ("A BIRD SINGS NOT BECAUSE IT HAS AN EXPLANATION, IT SINGS BECAUSE IT HAS A JOYFUL SONG.", "CHINESE PROVERB", "Joy"),
    ("BEING DEEPLY LOVED GIVES YOU STRENGTH, WHILE LOVING SOMEONE DEEPLY GIVES YOU COURAGE.", "LAO TZU", "Love"),
    ("CONVICTIONS ARE MORE DANGEROUS FOES OF FACTUAL TRUTH THAN DELIBERATE CALCULATION.", "FRIEDRICH NIETZSCHE", "Truth"),
    ("HE WHO LAUGHS AT HIMSELF NEVER RUNS OUT OF CHARMING THINGS TO BE THOROUGHLY AMUSED BY.", "EPICURUS", "Humor"),
    ("IF YOU WISH TO REACH THE HIGHEST PEAKS, BEGIN BY CONQUERING THE LOWEST VALLEYS.", "PUBLILIUS SYRUS", "Ambition"),
    ("MAN CONQUERS THE UNIVERSE WITH BOLD STEPS BUT REMAINS TOTALLY UNFAMILIAR WITH HIMSELF.", "PROVERB", "Philosophy"),
    ("THE SHORTEST DISTANCE BETWEEN TWO POINTS ON EARTH IS OFTEN AN ENTIRELY NEW PERSPECTIVE.", "PROVERB", "Perspective"),
    ("TO AVOID MISTAKES, GAIN EXPERIENCE; TO GAIN EXPERIENCE, MAKE A MULTITUDE OF MISTAKES.", "PROVERB", "Experience"),
    ("WHEN THE WINDS OF ADVERSITY BLOW, SOME BUILD DEFENSIVE WALLS WHILE OTHERS ERECT WINDMILLS.", "PROVERB", "Wisdom"),
    ("YOU CANNOT DISCOVER NEW OCEANS UNLESS YOU POSSESS COURAGE TO LOSE SIGHT OF THE SHORE.", "ANDRE GIDE", "Exploration"),
    ("ZEAL WITHOUT PRUDENCE IS LIKE A RUNAWAY STEED WITHOUT BRIDLE OR STEADY REINS.", "PROVERB", "Prudence"),
    ("A COMPROMISE IS DIVIDING A CAKE SO EVERYONE BELIEVES HE GOT THE BIGGEST PIECE.", "LUDWIG ERHARD", "Wit"),
    # 61-80
    ("FEAR DEFEATS MORE DREAMS THAN OUTRIGHT FAILURE COULD EVER HOPE TO ACCOMPLISH IN LIFE.", "SUZY KASSEM", "Fear"),
    ("GRATITUDE IS NOT ONLY THE GREATEST OF VIRTUES, BUT THE PROLIFIC PARENT OF ALL OTHERS.", "CICERO", "Gratitude"),
    ("HONESTY OFTEN PROVOKES HOSTILITY AMONG THOSE WHOSE PREJUDICES FLOURISH IN DECEIT.", "PROVERB", "Honesty"),
    ("INJUSTICE ANYWHERE IS A PROFOUND THREAT TO UNCHECKED JUSTICE EVERYWHERE ACROSS EARTH.", "MARTIN LUTHER KING JR.", "Justice"),
    ("JUDGMENT COMES FROM EXPERIENCE, AND EXPERIENCE SO FREQUENTLY SPRINGS FROM POOR JUDGMENT.", "MARK TWAIN", "Judgment"),
    ("KNOWLEDGE IS ACQUIRED BY DILIGENT STUDY, BUT WISDOM IS CULTIVATED THROUGH DEEP REVERENCE.", "PROVERB", "Knowledge"),
    ("LIBERTY CONSISTS IN THE FREEDOM TO DO EVERYTHING WHICH INJURES NO OTHER LIVING CITIZEN.", "FRENCH DECLARATION", "Liberty"),
    ("MODERATION IN ALL PURSUITS IS THE SAFEST GUARDIAN OF LONG-TERM HUMAN CONTENTMENT.", "PROVERB", "Moderation"),
    ("NO LEGACY IS SO RICH AS INTEGRITY SPREAD ABROAD ACROSS COMMODIOUS GENERATIONS.", "WILLIAM SHAKESPEARE", "Integrity"),
    ("OPPORTUNITY OFTEN COMES DISGUISED AS HARD LABOR, WHICH IS WHY SO FEW RECOGNIZE IT.", "ANN LANDERS", "Opportunity"),
    ("PATIENCE WITH FAMILY IS KIND LOVE, PATIENCE WITH ALL OTHERS IS REQUISITE RESPECT.", "PROVERB", "Patience"),
    ("QUIET CONVERSATIONS WITH ONE'S SOUL YIELD THE RICHEST FRUITS OF SOUND UNDERSTANDING.", "PROVERB", "Solitude"),
    ("REPUTATION IS WHAT MEN THINK YOU ARE; CONSCIENCE IS WHAT GOD AND ANGELS KNOW YOU BE.", "THOMAS PAINE", "Reputation"),
    ("SINCERITY AND ENTHUSIASM CAN CONQUER MOUNTAINS WHERE MERE BRILLIANCE OFTEN STUMBLES.", "PROVERB", "Sincerity"),
    ("THE ART OF BEING WISE IS THE ART OF KNOWING EXACTLY WHAT TO OVERLOOK IN CONTROVERSY.", "WILLIAM JAMES", "Wisdom"),
    ("UNSELFISH DEVOTION TO COMMON WELL-BEING IS THE HIGHEST CROWN OF MORAL EXCELLENCE.", "PROVERB", "Virtue"),
    ("VICTORY GAINED BY COERCION IS AKIN TO DEFEAT, FOR IT LACKS THE GENUINE CONSENT OF HEARTS.", "PROVERB", "Victory"),
    ("WISDOM EXCEEDS WEALTH AS THE SUN'S GLOWING MAJESTY OUTSHINES THE FAINTEST FLICKERING CANDLE.", "PROVERB", "Wisdom"),
    ("YOUTH MAY BE BLIND TO THE FUTURE, BUT AGE OFTEN TURNS BLIND EYES UPON THE LIVING PRESENT.", "PROVERB", "Age"),
    ("A CRITIC IS A LEGLESS TRAVELER WHO INSTRUCTS SWIFT RUNNERS HOW BEST TO SPRINT FORWARD.", "CHANNING POLLOCK", "Wit"),
    # 81-100
    ("BEWARE OF FALSE KNOWLEDGE; IT IS IMMENSELY MORE DANGEROUS TO REASON THAN OUTRIGHT IGNORANCE.", "GEORGE BERNARD SHAW", "Knowledge"),
    ("CHARACTER IS LIKE A SOLID TREE AND REPUTATION LIKE ITS SHADOW CAST BENEATH THE MIDDAY SUN.", "ABRAHAM LINCOLN", "Character"),
    ("DIGNITY DOES NOT CONSIST IN POSSESSING HIGH HONORS, BUT IN TRULY CONSCIOUS MERIT OF THEM.", "ARISTOTLE", "Dignity"),
    ("ENVY EATS NOTHING EXCEPT ITS OWN FRAIL HEART, CORRODING THE VESSEL IN WHICH IT IS STORED.", "PROVERB", "Envy"),
    ("FRIENDSHIP IS A SINGLE ENERGETIC SOUL DWELLING HARMONIOUSLY WITHIN TWO SEPARATE BODIES.", "ARISTOTLE", "Friendship"),
    ("GENIUS IS ONE PERCENT INVENTIVE INSPIRATION AND NINETY-NINE PERCENT RIGOROUS PERSPIRATION.", "THOMAS EDISON", "Genius"),
    ("HE WHO CANNOT BE A GOOD FOLLOWER CANNOT BE A TRULY INSPIRING COMMANDER OR LEADER.", "ARISTOTLE", "Leadership"),
    ("IMAGINATION IS MORE IMPORTANT THAN DRY KNOWLEDGE, FOR KNOWLEDGE IS STRICTLY LIMITED.", "ALBERT EINSTEIN", "Imagination"),
    ("JUSTICE WILL NOT BE SERVED UNTIL THOSE WHO ARE UNAFFECTED ARE AS OUTRAGED AS THE AFFLICTED.", "BENJAMIN FRANKLIN", "Justice"),
    ("KINDNESS IS A CURRENCY WHICH THE DEAF CAN HEAR CLEARLY AND THE BLIND CAN PLAINLY BEHOLD.", "MARK TWAIN", "Kindness"),
    ("LOVING SACRIFICE IS THE HIGHEST TESTAMENT OF DEVOTION KNOWN THROUGHOUT RECORDED HISTORY.", "PROVERB", "Sacrifice"),
    ("MAGNIFICENT RESULTS ARE NEVER PRODUCED EXCEPT BY COMMITTING EXTENSIVE PATIENT INDUSTRY.", "PROVERB", "Industry"),
    ("NOTHING IN LIFE IS TO BE FEARED; IT IS ONLY TO BE PATIENTLY AND THOROUGHLY UNDERSTOOD.", "MARIE CURIE", "Courage"),
    ("OBSTACLES ARE THOSE FRIGHTFUL THINGS YOU SEE WHEN YOU TAKE YOUR FOCUSED EYES OFF THE GOAL.", "HENRY FORD", "Focus"),
    ("PRIDE GOETH BEFORE DESTRUCTION, AND A HAUGHTY SPIRIT SWELLS BEFORE A DISASTROUS FALL.", "PROVERB", "Humility"),
    ("QUARRELS WOULD NOT LAST SO LONG IF SILLY FAULT WERE ONLY UPON ONE DISPUTING PARTY.", "FRANCOIS DE LA ROCHEFOUCAULD", "Peace"),
    ("REAL INTEGRITY IS DOING THE RIGHT THING EVEN WHEN KNOWING THAT NOBODY IS WATCHING YOU.", "C. S. LEWIS", "Integrity"),
    ("SOMETIMES THE QUESTIONS ARE COMPLICATED AND THE GENUINE ANSWERS ARE BEAUTIFULLY SIMPLE.", "DR. SEUSS", "Simplicity"),
    ("THE ONLY COMPREHENSIVE MISTAKE IN LIFE IS THE ONE FROM WHICH WE DERIVE ZERO WISDOM.", "HENRY FORD", "Learning"),
    ("UNJUST CONDEMNATION REBOUNDS WITH DOUBLE WEIGHT UPON THE HEAD OF THE WRONGFUL ACCUSER.", "PROVERB", "Justice"),
]

def clean_text(s: str) -> str:
    s = s.strip().upper()
    # Ensure proper spacing around punctuation
    s = re.sub(r'\s+', ' ', s)
    return s

def main():
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    json_path = os.path.join(root_dir, "server", "data", "cryptograms.json")
    cpp_header_path = os.path.join(root_dir, "esp32-firmware", "src", "generators", "CryptogramDataset.h")

    # Assemble JSON entries
    json_data = []

    print(f"Easy quotes: {len(EASY_QUOTES)}")
    print(f"Medium quotes: {len(MEDIUM_QUOTES)}")
    print(f"Hard quotes: {len(HARD_QUOTES)}")
    assert len(EASY_QUOTES) == 100, f"Expected 100 easy, got {len(EASY_QUOTES)}"
    assert len(MEDIUM_QUOTES) == 100, f"Expected 100 medium, got {len(MEDIUM_QUOTES)}"
    assert len(HARD_QUOTES) == 100, f"Expected 100 hard, got {len(HARD_QUOTES)}"

    for i, (p, a, cat) in enumerate(EASY_QUOTES, 1):
        p_clean = clean_text(p)
        a_clean = clean_text(a)
        json_data.append({
            "id": f"easy_{i:03d}",
            "diff": "easy",
            "phrase": p_clean,
            "author": a_clean,
            "category": cat
        })

    for i, (p, a, cat) in enumerate(MEDIUM_QUOTES, 1):
        p_clean = clean_text(p)
        a_clean = clean_text(a)
        json_data.append({
            "id": f"medium_{i:03d}",
            "diff": "medium",
            "phrase": p_clean,
            "author": a_clean,
            "category": cat
        })

    for i, (p, a, cat) in enumerate(HARD_QUOTES, 1):
        p_clean = clean_text(p)
        a_clean = clean_text(a)
        json_data.append({
            "id": f"hard_{i:03d}",
            "diff": "hard",
            "phrase": p_clean,
            "author": a_clean,
            "category": cat
        })

    # Write JSON
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(json_data, f, indent=2)
    print(f"Wrote {len(json_data)} quotes to {json_path}")

    # Generate C++ Header
    def escape_cpp(s: str) -> str:
        return s.replace('\\', '\\\\').replace('"', '\\"')

    lines = [
        "// Morning Puzzles - Offline Cryptogram Dataset",
        "// 300 Curated Quotes (100 Easy, 100 Medium, 100 Hard) stored in PROGMEM flash.",
        "// Auto-generated from server/data/cryptograms.json",
        "#ifndef CRYPTOGRAM_DATASET_H",
        "#define CRYPTOGRAM_DATASET_H",
        "",
        "#include <Arduino.h>",
        "",
        "struct CryptogramQuote {",
        "    const char* phrase;",
        "    const char* author;",
        "};",
        "",
        "static const size_t NUM_CRYPTOGRAMS_PER_DIFF = 100;",
        "static const size_t TOTAL_CRYPTOGRAM_PUZZLES = 300;",
        "",
        "static const CryptogramQuote EASY_CRYPTOGRAMS[NUM_CRYPTOGRAMS_PER_DIFF] PROGMEM = {"
    ]

    for p, a, _ in EASY_QUOTES:
        lines.append(f'    {{"{escape_cpp(clean_text(p))}", "{escape_cpp(clean_text(a))}"}},')
    lines.append("};")
    lines.append("")

    lines.append("static const CryptogramQuote MEDIUM_CRYPTOGRAMS[NUM_CRYPTOGRAMS_PER_DIFF] PROGMEM = {")
    for p, a, _ in MEDIUM_QUOTES:
        lines.append(f'    {{"{escape_cpp(clean_text(p))}", "{escape_cpp(clean_text(a))}"}},')
    lines.append("};")
    lines.append("")

    lines.append("static const CryptogramQuote HARD_CRYPTOGRAMS[NUM_CRYPTOGRAMS_PER_DIFF] PROGMEM = {")
    for p, a, _ in HARD_QUOTES:
        lines.append(f'    {{"{escape_cpp(clean_text(p))}", "{escape_cpp(clean_text(a))}"}},')
    lines.append("};")
    lines.append("")

    lines.append("#endif // CRYPTOGRAM_DATASET_H")
    lines.append("")

    with open(cpp_header_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote C++ header to {cpp_header_path}")

if __name__ == "__main__":
    main()
